#ifndef OPTIMIZER_METADATA_POINTS_TO_HPP_INCLUDED
#define OPTIMIZER_METADATA_POINTS_TO_HPP_INCLUDED

#include <functional>
#include <optimizer/metadata/meta_entry.hpp>
#include <optimizer/programIR/constant_ir.hpp>
#include <optimizer/programIR/function_ir.hpp>
#include <optimizer/programIR/ir_types.hpp>
#include <optimizer/programIR/program_ir.hpp>
#include <optimizer/programIR/variable_ir.hpp>
#include <optimizer/utils/points_to/defines.hpp>
#include <utility/assumptions.hpp>

#include <map>

namespace optimizer::metadata::points_to
{
namespace utils = utils::points_to;
using utils::MaySet;
using utils::MayState;
using utils::MustState;
using utils::objectId;
using utils::ObjectPool;
using utils::Target;

template <typename BaseEntryI>
    requires std::derived_from<BaseEntryI, MetaEntryI>
using PointsToMetaEntry = ConcreteMetaEntry<BaseEntryI, MetaKey::POINTS_TO>;

struct ConstantMeta final : PointsToMetaEntry<ConstantMetaEntryI>
{
    // assigned object id
    objectId id = utils::grouped_objects::UNDEFINED;
};

struct InstructionMeta final : PointsToMetaEntry<InstructionMetaEntryI>
{
    // TODO: remove this and in serialize points to replace with queries
    // Must state before instruction
    // MustState must_in;
    // // May state before instruction
    // MayState may_in;
};

struct VariableMeta final : PointsToMetaEntry<VariableMetaEntryI>
{
    objectId id = utils::grouped_objects::UNDEFINED;
};

struct BasicBlockMeta final : PointsToMetaEntry<BasicBlockMetaEntryI>
{
    MustState must_in;
    MayState  may_in;
};

// Generated by LocalPointsToAnalysis
struct FunctionMeta final : PointsToMetaEntry<FunctionMetaEntryI>
{
    // Contains objects which are not in global_objects and are relevant in the conext of
    // the function
    ObjectPool local_objects;
};

// Generated by GlobalPointsToAnalysis
struct ProgramMeta final : PointsToMetaEntry<ProgramMetaEntryI>
{
    // id -> ConstantIR_wptr/static VariableIR_wptr
    // std::map<int, std::variant<program::VariableIR_wptr, program::ConstantIR_wptr>> id_to_global;

    // Mapping of object IDs to global scope variables (static, constants)
    // std::map<objectId, program::VariableIR_wptr> id_to_variable;

    // Contains objects with global scope
    MustState  must_out;
    MayState   may_out;
    ObjectPool global_objects;

    // transfer functions used
    std::function<void(const utils::MayTransferContextBundle& context)>  transfer_may_;
    std::function<void(const utils::MustTransferContextBundle& context)> transfer_must_;

    void clear_context()
    {
        must_out.clear();
        may_out.clear();
        // id_to_variable.clear();
    }
};
} // namespace optimizer::metadata::points_to

#endif
