#ifndef OPTIMIZER_METADATA_POINTS_TO_HPP_INCLUDED
#define OPTIMIZER_METADATA_POINTS_TO_HPP_INCLUDED

#include <functional>
#include <optimizer/metadata/meta_entry.hpp>
#include <optimizer/programIR/constant_ir.hpp>
#include <optimizer/programIR/function_ir.hpp>
#include <optimizer/programIR/ir_types.hpp>
#include <optimizer/programIR/program_ir.hpp>
#include <optimizer/programIR/variable_ir.hpp>
#include <optimizer/utils/points_to/basic_block_may_state_store.hpp>
#include <optimizer/utils/points_to/defines.hpp>
#include <utility/assumptions.hpp>

#include <memory>

namespace optimizer::metadata::points_to
{
namespace utils = utils::points_to;
using utils::BasicBlockMayStateStore;
using utils::MayAnalysisState;
using utils::MayState;
using utils::objectId;
using utils::ObjectPool;
using utils::StateId;
using utils::Target;

template <typename BaseEntryI>
    requires std::derived_from<BaseEntryI, MetaEntryI>
using PointsToMetaEntry = ConcreteMetaEntry<BaseEntryI, MetaKey::POINTS_TO>;

struct ConstantMeta final : PointsToMetaEntry<ConstantMetaEntryI>
{
    // assigned object id
    objectId id{};
};

struct InstructionMeta final : PointsToMetaEntry<InstructionMetaEntryI>
{
    // TODO: remove this and in serialize points to replace with queries
    // Must state before instruction
    // MustState must_in;
    // // May state before instruction
    // MayState may_in;
};

struct VariableMeta final : PointsToMetaEntry<VariableMetaEntryI>
{
    objectId id{};
};

struct BasicBlockMeta final : PointsToMetaEntry<BasicBlockMetaEntryI>
{
    StateId may_in_id{0};
};

// Generated by LocalPointsToAnalysis
struct FunctionMeta final : PointsToMetaEntry<FunctionMetaEntryI>
{
    // Contains objects which are not in global_objects and are relevant in the conext of
    // the function
    ObjectPool                               local_objects;
    std::shared_ptr<BasicBlockMayStateStore> bb_may_state_store;
};

struct ProgramMeta final : PointsToMetaEntry<ProgramMetaEntryI>
{
    MayAnalysisState may_out;
    ObjectPool       global_objects;

    std::function<void(const utils::MayTransferContextBundle& context)> transfer_may_;
};
} // namespace optimizer::metadata::points_to

#endif
